services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception_network
    ports:
      - "3306:3306"

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: on-failure
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
    volumes:
      - ./volumes/wordpress_volume:/var/www/html
    networks:
      - inception_network
    ports:
      - "9000:9000"
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: on-failure
    env_file: .env
    volumes:
      - ./volumes/wordpress_volume:/var/www/html
    networks:
      - inception_network
    ports:
      - "443:443"
    depends_on:
      - wordpress

networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_volume:
