services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    env_file: .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception_network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: password

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: on-failure
    env_file: .env
    volumes:
      - ./volumes/wordpress_volume:/var/www/html
    networks:
      - inception_network
    ports:
      - "9000:9000"
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: on-failure
    env_file: .env
    volumes:
      - ./volumes/wordpress_volume:/var/www/html
    networks:
      - inception_network
    ports:
      - "443:443"
    depends_on:
      - wordpress

networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_volume:
